name: Flow Validation
on:
  push:
    branches: [main, master]
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - uses: actions-cool/check-user-permission@main
        id: checkUser
        with:
          username: ${{github.triggering_actor}}
          require: 'write'
      - if: ${{ steps.checkUser.outputs.require-result == 'false' }}
        run: |
          echo "::error::!! ${{ github.actor }} is an external user, a team member must retry this build" \
          | tee -a $GITHUB_STEP_SUMMARY && exit 1
      - name: Check secrets
        run: |
          [ -z "${{secrets.TB_LICENSE}}" ] \
            && echo "::error::!! NO TB_LICENSE: Check that this repo has a valid TB_LICENSE secret" \
            | tee -a $GITHUB_STEP_SUMMARY && exit 1 || exit 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}          
      - name: Compile and Install
        run: |
          cmd="mvn install -B -ntp -DskipTests"
          eval $cmd -T 2C -q || eval $cmd
