name: Flow Validation
on:
  push:
    branches: [main, master]
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - uses: actions-cool/check-user-permission@main
        id: checkUser
        with:
          require: 'write'
      - name: close
        if: steps.checkUser.outputs.check-result == 'false'
        run: echo "${{ github.actor }} is an external user" | tee -a $GITHUB_STEP_SUMMARY && exit 1
      - name: Check secrets
        run: |
          TB_LICENSE="${{secrets.TB_LICENSE}}"
          [ -z "$TB_LICENSE" ] \
            && echo "::error::!! ERROR NO TB_LICENSE: Check that this repo has a valid TB_LICENSE secret !!" \
            && exit 1 || exit 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}          
      - name: Compile and Install
        run: |
          cmd="mvn install -B -ntp -DskipTests"
          eval $cmd -T 2C -q || eval $cmd
